import { Providers } from "@/src/client/components/providers";
import { SiteFooter } from "@/src/client/components/site-footer";
import { SiteHeader } from "@/src/client/components/site-header";
import { TailwindIndicator } from "@/src/client/components/tailwind-indicator";
import { cn } from "@/src/client/utils/cn";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  fallback: ["Arial", "sans-serif"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background antialiased",
          roboto.className
        )}
      >
        <Providers>
          <div className="relative flex min-h-screen flex-col">
            <SiteHeader />
            <div className="flex flex-1 flex-col">{children}</div>
            <SiteFooter />
          </div>
          <TailwindIndicator />
        </Providers>
      </body>
    </html>
  );
}
