import "./globals.css";
import { Inter } from "next/font/google";
import {
  AuthProvider,
  ThemeProvider,
  TrpcProvider,
} from "@/components/providers";
import { cn } from "@/lib/utils";
import { TailwindIndicator } from "@/components/tailwind-indicator";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.className
        )}
      >
        <AuthProvider>
          <TrpcProvider>
            <ThemeProvider>
              <div className="relative flex min-h-screen flex-col">
                <SiteHeader />
                <div className="flex flex-1">{children}</div>
                <SiteFooter />
              </div>
              <TailwindIndicator />
            </ThemeProvider>
          </TrpcProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
