import "./globals.css";
import { Roboto } from "next/font/google";
import {
  AuthProvider,
  ThemeProvider,
  TrpcProvider,
} from "@/components/providers";
import { cn } from "@/lib/utils/cn";
import { TailwindIndicator } from "@/components/tailwind-indicator";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  fallback: ["Arial", "sans-serif"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background antialiased",
          roboto.className
        )}
      >
        <AuthProvider>
          <TrpcProvider>
            <ThemeProvider>
              <div className="relative flex min-h-screen flex-col">
                <SiteHeader />
                <div className="flex flex-1 flex-col">{children}</div>
                <SiteFooter />
              </div>
              <TailwindIndicator />
            </ThemeProvider>
          </TrpcProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
